// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.developer.loadtesting.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The FileUrlList model. */
@Fluent
public final class FileUrlList {
    /*
     * List of file URLs.
     */
    @JsonProperty(value = "value", required = true)
    private List<FileUrl> value;

    /*
     * Link for the next list of file URLs, if applicable
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Get the value property: List of file URLs.
     *
     * @return the value value.
     */
    public List<FileUrl> getValue() {
        return this.value;
    }

    /**
     * Set the value property: List of file URLs.
     *
     * @param value the value value to set.
     * @return the FileUrlList object itself.
     */
    public FileUrlList setValue(List<FileUrl> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink property: Link for the next list of file URLs, if applicable.
     *
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: Link for the next list of file URLs, if applicable.
     *
     * @param nextLink the nextLink value to set.
     * @return the FileUrlList object itself.
     */
    public FileUrlList setNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }
}
