// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.developer.loadtesting.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.nio.ByteBuffer;
import reactor.core.publisher.Flux;

/** The Paths73K4RbLoadtestsTestidFilesFileidPutRequestbodyContentMultipartFormDataSchema model. */
@Fluent
public final class Paths73K4RbLoadtestsTestidFilesFileidPutRequestbodyContentMultipartFormDataSchema {
    /*
     * The file to be uploaded.
     */
    @JsonProperty(value = "file", required = true)
    private Flux<ByteBuffer> file;

    /**
     * Get the file property: The file to be uploaded.
     *
     * @return the file value.
     */
    public Flux<ByteBuffer> getFile() {
        return this.file;
    }

    /**
     * Set the file property: The file to be uploaded.
     *
     * @param file the file value to set.
     * @return the Paths73K4RbLoadtestsTestidFilesFileidPutRequestbodyContentMultipartFormDataSchema object itself.
     */
    public Paths73K4RbLoadtestsTestidFilesFileidPutRequestbodyContentMultipartFormDataSchema setFile(
            Flux<ByteBuffer> file) {
        this.file = file;
        return this;
    }
}
