// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.developer.loadtesting.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Associated metric definition for particular metrics of the azure resource ( Refer :
 * https://docs.microsoft.com/en-us/rest/api/monitor/metric-definitions/list#metricdefinition).
 */
@Fluent
public final class ResourceMetricModel {
    /*
     * Unique identifier for metric.
     */
    @JsonProperty(value = "id", access = JsonProperty.Access.WRITE_ONLY)
    private String id;

    /*
     * Azure resource Id.
     */
    @JsonProperty(value = "resourceId", required = true)
    private String resourceId;

    /*
     * Metric name space.
     */
    @JsonProperty(value = "metricnamespace", required = true)
    private String metricnamespace;

    /*
     * Metric description.
     */
    @JsonProperty(value = "displayDescription")
    private String displayDescription;

    /*
     * Metric name object.
     */
    @JsonProperty(value = "name", required = true)
    private ServerMetricName name;

    /*
     * Metric aggregation.
     */
    @JsonProperty(value = "aggregation", required = true)
    private String aggregation;

    /*
     * Metric unit.
     */
    @JsonProperty(value = "unit")
    private String unit;

    /*
     * Azure resource type.
     */
    @JsonProperty(value = "resourceType", required = true)
    private String resourceType;

    /**
     * Get the id property: Unique identifier for metric.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Get the resourceId property: Azure resource Id.
     *
     * @return the resourceId value.
     */
    public String getResourceId() {
        return this.resourceId;
    }

    /**
     * Set the resourceId property: Azure resource Id.
     *
     * @param resourceId the resourceId value to set.
     * @return the ResourceMetricModel object itself.
     */
    public ResourceMetricModel setResourceId(String resourceId) {
        this.resourceId = resourceId;
        return this;
    }

    /**
     * Get the metricnamespace property: Metric name space.
     *
     * @return the metricnamespace value.
     */
    public String getMetricnamespace() {
        return this.metricnamespace;
    }

    /**
     * Set the metricnamespace property: Metric name space.
     *
     * @param metricnamespace the metricnamespace value to set.
     * @return the ResourceMetricModel object itself.
     */
    public ResourceMetricModel setMetricnamespace(String metricnamespace) {
        this.metricnamespace = metricnamespace;
        return this;
    }

    /**
     * Get the displayDescription property: Metric description.
     *
     * @return the displayDescription value.
     */
    public String getDisplayDescription() {
        return this.displayDescription;
    }

    /**
     * Set the displayDescription property: Metric description.
     *
     * @param displayDescription the displayDescription value to set.
     * @return the ResourceMetricModel object itself.
     */
    public ResourceMetricModel setDisplayDescription(String displayDescription) {
        this.displayDescription = displayDescription;
        return this;
    }

    /**
     * Get the name property: Metric name object.
     *
     * @return the name value.
     */
    public ServerMetricName getName() {
        return this.name;
    }

    /**
     * Set the name property: Metric name object.
     *
     * @param name the name value to set.
     * @return the ResourceMetricModel object itself.
     */
    public ResourceMetricModel setName(ServerMetricName name) {
        this.name = name;
        return this;
    }

    /**
     * Get the aggregation property: Metric aggregation.
     *
     * @return the aggregation value.
     */
    public String getAggregation() {
        return this.aggregation;
    }

    /**
     * Set the aggregation property: Metric aggregation.
     *
     * @param aggregation the aggregation value to set.
     * @return the ResourceMetricModel object itself.
     */
    public ResourceMetricModel setAggregation(String aggregation) {
        this.aggregation = aggregation;
        return this;
    }

    /**
     * Get the unit property: Metric unit.
     *
     * @return the unit value.
     */
    public String getUnit() {
        return this.unit;
    }

    /**
     * Set the unit property: Metric unit.
     *
     * @param unit the unit value to set.
     * @return the ResourceMetricModel object itself.
     */
    public ResourceMetricModel setUnit(String unit) {
        this.unit = unit;
        return this;
    }

    /**
     * Get the resourceType property: Azure resource type.
     *
     * @return the resourceType value.
     */
    public String getResourceType() {
        return this.resourceType;
    }

    /**
     * Set the resourceType property: Azure resource type.
     *
     * @param resourceType the resourceType value to set.
     * @return the ResourceMetricModel object itself.
     */
    public ResourceMetricModel setResourceType(String resourceType) {
        this.resourceType = resourceType;
        return this;
    }
}
