// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.developer.loadtesting.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Metric name object. */
@Fluent
public final class ServerMetricName {
    /*
     * Metric name value.
     */
    @JsonProperty(value = "value", required = true)
    private String value;

    /*
     * Metric localized name.
     */
    @JsonProperty(value = "localizedValue", required = true)
    private String localizedValue;

    /**
     * Get the value property: Metric name value.
     *
     * @return the value value.
     */
    public String getValue() {
        return this.value;
    }

    /**
     * Set the value property: Metric name value.
     *
     * @param value the value value to set.
     * @return the ServerMetricName object itself.
     */
    public ServerMetricName setValue(String value) {
        this.value = value;
        return this;
    }

    /**
     * Get the localizedValue property: Metric localized name.
     *
     * @return the localizedValue value.
     */
    public String getLocalizedValue() {
        return this.localizedValue;
    }

    /**
     * Set the localizedValue property: Metric localized name.
     *
     * @param localizedValue the localizedValue value to set.
     * @return the ServerMetricName object itself.
     */
    public ServerMetricName setLocalizedValue(String localizedValue) {
        this.localizedValue = localizedValue;
        return this;
    }
}
